### ISSUE TITLE
`pg_sphere_version()` reports version that is different from extension version.

### ISSUE THREAD

**Issue by andy-slac** [postgrespro/pgsphere#10]
With just installed `pg_shere` from current master, and we observe difference in reported version numbers between `pg_sphere_version()` and extension version:
```
=> select pg_sphere_version();
 pg_sphere_version
-------------------
 1.1.5

=> SELECT extversion from pg_catalog.pg_extension where extname = 'pg_sphere';
 extversion
------------
 1.2.0
```
Aren't they supposed to be the same?

**Comment by vitcpp** [comment]
PR #23 is prepared.
