### ISSUE TITLE
Make New Release 1.4.2

### ISSUE THREAD

**Issue by vitcpp** [postgrespro/pgsphere#115]
There are some changes for a new release:
* Rollback some changes to fix polygon creation (@vitcpp)
* Fix dist rule in the Makefile (@pdowler)
* Implement KNN algorithm for spoints (@waaeer)

The last commit was pushed directly into the master branch by mistake. The master branch is a dev branch. I propose to keep the last commit and test it directly in master, once it is already committed.

P.S. I will check that the master branch is protected and protect it if not.

**Comment by esabol** [comment]
I'd like to see a couple minor tweaks made to the "KNN support for spoints" commit.

doc/indices.sgm: Change "fast finding" to "quickly finding". Also, the commit deleted a blank line before the `</sect1>`, and that line shouldn't have been deleted.

pgs_gist.sql.in: The "17" in "OPERATOR 17" should line up with the "16" on the previous line, please.

And an upgrade script is needed, of course.

**Comment by vitcpp** [comment]
@esabol There is another idea. I think to remove it from the master branch (force push or revert). Create a PR with this commit. The fixes will be done in this PR. The authorship of @waaeer will be preserved. It allows to work as usual. If no objections, I will go this way.

**Comment by pdowler** [comment]
I think the other two changes (makefile and spoly validation) would be a 1.4.2 release that's valuable now.

Then the KNN work is a new feature to show up in  1.5 or later depending on what happens.

**Comment by vitcpp** [comment]
@pdowler Thank you for your opinion! I agree. If no objections I will rollback KNN from the master branch and create a new release 1.4.2 with polygon fixes. KNN will go to the next release (1.5.0) as a separate PR.

@esabol Do you have any objections?

**Comment by esabol** [comment]
> @esabol Do you have any objections?

No, no objections. It's fine. Thank you!

**Comment by vitcpp** [comment]
Status update:
- knn commit was removed from the master
- dist rule PR was merged
- knn PR was created for review and improvement (for the upcoming 1.5.0 release)

I propose to make 1.4.2 version artifact from the current code snapshot.

**Comment by vitcpp** [comment]
Do you have any objections against bumping 1.4.2 as the latest release?

**Comment by esabol** [comment]
@vitcpp asked:
> Do you have any objections against bumping 1.4.2 as the latest release?

No objections.

**Comment by vitcpp** [comment]
Closed as completed.
