### ISSUE TITLE
Make a new Release 1.5.1

### ISSUE THREAD

**Issue by vitcpp** [postgrespro/pgsphere#120]
Dear All, 

I think, it is the time for a new release. Do you have any objections?

**Comment by esabol** [comment]
Sounds good to me. Thank you, @vitcpp !

**Comment by vitcpp** [comment]
@esabol It is up to us. I apologize, I delayed the release due to some circumstances (lots of other work). I just wanted to do some more testing of upgrade before creating a new release. I'm going to do it for 1 - 2 days.

**Comment by esabol** [comment]
No need to apologize. It's a sensible course of action. May I ask a favor? When the pre-release becomes an official release, could you post a message here? I'm afraid GitHub will not send another notification. That has happened for me in the past with pre-releases.

**Comment by vitcpp** [comment]
@esabol Yes, sure. I will do that.

**Comment by vitcpp** [comment]
Some problems were found in 1.5.0. The new release candidate version is 1.5.1.

**Comment by vitcpp** [comment]
Dear All,

The Release 1.5.1 is published. Thank you for all your interest and contribution.

**Comment by vitcpp** [comment]
@esabol The new release is published. Thank you very much for your contribution!

**Comment by vitcpp** [comment]
Closed as completed.

**Comment by esabol** [comment]
I just upgraded our servers from 1.4.2 to 1.5.1. I was a bit surprised that the tests all passed before I actually executed `ALTER EXTENSION pg_sphere UPDATE TO '1.5.1';` (but after I `make install`ed). Is that to be expected?

**Comment by vitcpp** [comment]
@esabol Not sure about it. Could you please provide some details? How did you run the tests?

**Comment by esabol** [comment]
I'm not doing anything unusual, @vitcpp.
```
make USE_HEALPIX=0
make USE_HEALPIX=0 install
env PGUSER=postgres make USE_HEALPIX=0 installcheck
env PGUSER=postgres make USE_HEALPIX=0 crushtest
```

**Comment by vitcpp** [comment]
@esabol, I think, everything is ok. The extension is bound to a database, not to the cluster as a whole. The target installcheck works with the running cluster. It creates and uses a special database contrib_regression for testing purposes. All the tests are running under this database. The first test init.sql executes CREATE EXTENSION statement which loads the extension in the current database (contrib_regression). Once you've installed a new version of pg_sphere, the create extension statement picks this new version. I guess, your other databases are untouched by tests, so, they may contain pgsphere schemas of a previous version. I think, it explains why installcheck works without errors at your side. Please, let me know if you need more clarification.

**Comment by esabol** [comment]
OK. Thanks for the explanation. That makes sense.
