### ISSUE TITLE
Improve versioning of pgsphere

### ISSUE THREAD

**Issue by vitcpp** [postgrespro/pgsphere#20]
Introduce releases

**Comment by vitcpp** [comment]
Dear All, I would like to agree on versioning of pgsphere:

- In general, we should follow some principles described in https://semver.org/
- Major number is for API incompatible changes.
- Minor number is for API backward compatible changes (old user sql should work with newest pgsphere).
- Patch number is for bug fixes (API is untouched).
- Mark each version with annotated tag like v1.2.0

What I'm concerned, now we increment only the third number (patch number) for those changes that include API changes. I guess we should increment minor number in this case. But if we decide to increment minor number on each API small change this number may become too big.

Another issue is an optional compilation of some parts like healpix. I do not exclude that some new optional compilation will appear in the near future. I think it should be the user responsibility how to compile. The version number should not reflect how pgsphere is compiled. I see the only issue - upgrade scripts. I guess we may implement some query function that returns the list of compiled features. It may help upgrade script to decide what to do.

I appreciate any comments, thank you!

**Comment by vitcpp** [comment]
It seems this issue is a duplicate of #9. Closing it.

**Comment by esabol** [comment]
> It seems this issue is a duplicate of #9. Closing it.

I didn't see these as duplicates, but I'm ok with combining them. I thought this issue was for releasing new versions at https://github.com/postgrespro/pgsphere/releases. I thought issue #9 was going back in the commit history of repository and tagging old releases.

**Comment by esabol** [comment]
> Well, I thought that it is a single complex problem with versions.

Yes, I agree with that.
