### ISSUE TITLE
Add BRIN support for spoint and sbox?

### ISSUE THREAD

**Issue by esabol** [postgrespro/pgsphere#52]
Would incorporating [this PR](https://github.com/akorotkov/pgsphere/pull/8) be useful to anyone? It was fully working but never merged. It seems a waste to not retain this functionality, and it could be a real benefit when dealing with very large tables with millions of points.

See https://github.com/akorotkov/pgsphere/pull/8 and [this comment](https://github.com/akorotkov/pgsphere/pull/8#issuecomment-1678048432).

**Comment by gbroccolo** [comment]
Hi, I see @vitcpp already opened a PR here (will leave comments there eventually). I'm happy to help if needed.

**Comment by vitcpp** [comment]
@gbroccolo Thank you for the patch! I preserved your authorship of the patch with some code adjustments. I believe, you don't mind if the patch will be applied in this repo. We also appreciate it if you will open some new PRs in this repo that seems to be the only alive repo of the pgSphere project.

**Comment by gbroccolo** [comment]
Hi @vitcpp fine. Will try to open new PRs, each one for each spherical geometry, any sooner. I will probably start with the circular type, as requested by @esabol.
