### ISSUE TITLE
Prepare 1.3.0 release

### ISSUE THREAD

**Issue by vitcpp** [postgrespro/pgsphere#58]
Deal All, I think we are close to release 1.3.0 version.

I would like to do some polishing to complete 1.3.0:

- Polish some upgrade scripts to avoid code duplication
- Test upgrade scripts
- Investigate and remove init_test

Please, let me know if you think that the release is not ready. What changes should be implemented as well? Thank you.

**Comment by esabol** [comment]
> I think we are close to release 1.3.0 version.

I agree!

**Comment by vitcpp** [comment]
I propose to keep init_test because it tests schema creation SQL but it should be improved in the future.

**Comment by vitcpp** [comment]
Found an issue with the upgrade script (#59).

**Comment by esabol** [comment]
> I think, release 1.3.0 is ready. I propose to create the release tag.

I agree!

**Comment by vitcpp** [comment]
Dear Sirs, the Release 1.3.0 is published. Thank you very much for the contributions and reviews!
