### ISSUE TITLE
Populate "About" area of repository with useful information

### ISSUE THREAD

**Issue by esabol** [postgrespro/pgsphere#76]
![Screen Shot 2023-10-04 at 2 10 07 PM](https://github.com/postgrespro/pgsphere/assets/22986767/6875c3a9-386a-480c-aba9-12c9121d7d41)

The "About" area for the repository currently displays "_No description, website, or topics provided._" I think it would be a good idea to put some useful information in there about the project.

**Comment by esabol** [comment]
I like the description that was added to the "About", but it's missing a period at the end. Please add a period to the end of that sentence.

I would also like to see a link to or the URL of the GitHub Pages documentation URL added to the "About" area.

**Comment by vitcpp** [comment]
@esabol Sure, thanks. I will add period.

Not sure, what do you propose concerning url? I've added the url to pgsphere.org. It is appeared under the About section. It is proposed to to be the primary project place. Now it redirects to the GitHub Pages. Later, a simple site will be implemented with some information and documentation about the project.

**Comment by esabol** [comment]
I didn't know pgsphere.org worked! I was just thinking a link to https://postgrespro.github.io/pgsphere/, but whichever.
