### ISSUE TITLE
Prepare Release 1.4.0

### ISSUE THREAD

**Issue by vitcpp** [postgrespro/pgsphere#98]
Dear Community,

I new release 1.4.0 is coming. I would propose to implement the following functionality to be included into the release:

PRs are proposed to be applied:
- #96 (in review)
- #71

New functions are proposed for implementation:
- spoly(spoint[])

**Comment by esabol** [comment]
I would just call it 1.3.2, since the repo is already set to make the next version be 1.3.2, but that's just me. I don't really care what the version number is.

I would like to see PR #96 and PR #99 included for sure. Thank you!

**Comment by vitcpp** [comment]
Due to the adopted versioning approach (semver.org) we have to increment the minor number because we have changes in the SQL interface. The patch number is incremented when doing some changes that do not affect the interfaces. The last PR before the release will change version to 1.4.0.

**Comment by esabol** [comment]
> Due to the adopted versioning approach (semver.org) we have to increment the minor number because we have changes in the SQL interface.

Oh, yes, of course.

**Comment by vitcpp** [comment]
PR #102 to be included into 1.4.0

**Comment by vitcpp** [comment]
All pending 1.4.0 PRs are merged. Freeze the code for testing. The 1.4.0 tag will be assigned after some testing.

**Comment by vitcpp** [comment]
I think 1.4.0 is ok. If no objections, I'm going to set a tag and create a release artifact.

**Comment by vitcpp** [comment]
Closed as completed.

**Comment by vitcpp** [comment]
@df7cb, @esabol, @borodun The new release 1.4.0 is done. Thank you very much for your contribution!
